import Link from "next/link";
import { getPeople, getRelationships } from "@/lib/data";
import { canonicalUrl } from "@/lib/seo";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Methodology",
  description:
    "How Papal Succession sources pope records, pontificate dates, and documented or traditional succession links.",
  alternates: { canonical: canonicalUrl("/about") },
  openGraph: {
    title: "Methodology",
    description:
      "How Papal Succession sources pope records, pontificate dates, and documented or traditional succession links.",
    url: canonicalUrl("/about"),
    type: "article",
  },
};

export default function About() {
  const people = getPeople();
  const rels = getRelationships();
  const docCount = rels.filter((r) => r.strength === "documented").length;
  const tradCount = rels.filter((r) => r.strength === "tradition").length;

  return (
    <article className="max-w-3xl mx-auto px-4 py-12 text-ink/80 leading-relaxed">
      <Link href="/" className="text-sm text-ink/60 hover:text-accent">
        ← Succession
      </Link>
      <h1 className="font-serif text-5xl mt-4 mb-6 text-ink">Methodology</h1>

      <p className="mb-6">
        This site maps {people.length} popes and {rels.length} immediate succession links from Peter
        to the current pope. The core source is the Holy See's public Pontiffs table, which lists
        papal name, beginning and end of pontificate, secular name, birthplace, and century.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-3 text-ink">What the dates mean</h2>
      <p className="mb-6">
        Timeline bars show <em>pontificates</em>, not lifespans. When the Holy See gives a date range
        with alternatives or ellipses, this site keeps that notation in the visible label and uses a
        single year only for chart placement. Peter's beginning is shown as c. 30 because the Holy
        See table leaves the beginning blank while giving the end as 64 or 67.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-3 text-ink">Evidence labels</h2>
      <ul className="space-y-3 mb-6">
        <li>
          <strong className="text-ink">Documented ({docCount}).</strong> Later succession links are drawn
          as documented because the Holy See table supplies the ordered list and pontificate dates.
        </li>
        <li>
          <strong className="text-ink">Tradition ({tradCount}).</strong> The earliest Roman succession is
          marked as tradition. The sequence is ancient and official, but the first centuries contain
          thinner documentary evidence and more date uncertainty.
        </li>
      </ul>

      <h2 className="font-serif text-2xl mt-8 mb-3 text-ink">Scope</h2>
      <p className="mb-6">
        This first version is popes only. The data model still uses people and relationships, so it can
        be expanded later to include other bishops, sees, disputed claimants, councils, or ordination
        links without throwing away the timeline and pope pages.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-3 text-ink">Source</h2>
      <p>
        Source data is generated by <code className="bg-ink/10 px-1 rounded">scripts/build-pope-data.mjs</code>{" "}
        from{" "}
        <a
          href="https://www.vatican.va/content/vatican/en/holy-father.html"
          className="underline decoration-ink/20 underline-offset-4 hover:text-accent"
        >
          The Holy See, Pontiffs
        </a>
        .
      </p>
    </article>
  );
}
